[project]
name = "prodoscore-automation-test"
version = "0.0.1"
description = "Prodoscore automation test suite"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prodoscore-automation-library==0.0.1",
]
#dependencies = [
#    "prodoscore-automation-library",
#]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["automation_test"]

[tool.uv.sources]
prodoscore-automation-library = { path = "../prodoscore-automation-library/dist/prodoscore_automation_library-0.0.1-py3-none-any.whl" }
# [tool.uv.sources]
# prodoscore-automation-library = { path = "../prodoscore-automation-library", editable = true }