# Test Settings Configuration
environment: staging
base_url: https://your-app.com

# Browser Settings
browser:
  type: chromium
  headless: false
  timeout: 30000

# Database Configuration (optional)
db:
  host: localhost
  port: 3310
  database: prodoapp_db_stg02
  user: is.weerasinghe
  password: ""
  pool_size: 2

# Test Data
test_data:
  number_of_employees: 6

# Domain details
domain:
  id: 918
  admin_email: JimJames@Prodoscore904.onmicrosoft.com

# Employee details
user:
  login_user:
    id: 329355

# Services details
api_clients:
  prodoscore_crypto:
    base_url: http://localhost:8087
